### ISSUE TITLE
Problem in Sticky header in crusher-app

### ISSUE THREAD

**Issue by hardikhere** [crusherdev/crusher#159]
**Describe the issue*
![Screenshot from 2021-09-20 16-11-39](https://user-images.githubusercontent.com/51117080/133990427-4bc43682-bed9-4b98-ad33-ac06fa5c8679.png)
*
Sticky header is remained sticky after scrolling up on route /app/build/[build id]

**Any loom video for this**
https://www.loom.com/share/d4c169b6a58b448e8e979ca90b3d2083

**What's expected behavior**
it should not be sticky on scroll up

**Who should solve this**
I can 
**Describe priority**

**Comment by himanshu-dixit** [comment]
Closed by #165
