### ISSUE TITLE
Bug: While running in local mode, result prompt is showing passed status

### ISSUE THREAD

**Issue by himanshu-dixit** [crusherdev/crusher#265]
Currently after running failed test. This prompt is shown.
<img width="353" alt="Screenshot 2022-08-08 at 10 35 36 PM" src="https://user-images.githubusercontent.com/6849438/183474529-56af9090-8a21-461c-8aa2-fcc3985c9b9d.png">

**Comment by utkarsh-dixit** [comment]
Closing this off. Fixed in #268
